config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    # root 'searches#show'

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_departure, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :routes do
      resources :railway_stations_routes
    end

    resources :tickets, except: [:new, :create]
  end

  resource :search, only: [:show]
  resources :tickets, except: [:edit, :update]
  resources :trains, only: [:index, :show]
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :title, presence: true
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
    @stations = @route.railway_stations
    @trains = @route.trains
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to [:admin, @route], notice: "Путь успешно создан."
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to [:admin, @route], notice: "Путь успешно изменен."
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path, notice: "Путь успешно удален."
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title)
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for([:admin, @route]) do |f| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit', action: @route.new_record? ? 'Создать' : 'Изменить') %>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td><%= route.title %></td>
  <td><%= link_to t('common.show'), [:admin, route] %></td>
  <td><%= link_to t('common.edit'), edit_admin_route_path(route) %></td>
  <td><%= link_to t('common.delete'), [:admin, route], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/routes/edit.html.erb
<h1>Редактировать маршрут</h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1>Список путей</h1>

<table class="table table-condensed">
  <tr>
    <th>Название</th>
    <th colspan="3"></th>
  </tr>
  <%= render @routes %>
</table>

<br>

<%= link_to 'Добавить путь', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/show.html.erb
<%=	render 'common/errors', resource: @route %>

<p>
  <strong>Название:</strong> <%= @route.title %>
</p>

<p>
  <strong>Станции:</strong>
  <% if @stations.empty? %>
    Список пуст
  <% else %>
    <table class="table">
      <thead>
      <tr>
        <td width="100px">Название</td>
        <td>Позиция</td>
        <td>Прибытие / Отправление</td>
      </tr>
      </thead>
      <tbody>
      <% @stations.ordered.each do |station| %>
          <tr>
            <td><%= station.title %></td>
            <td>
              <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
                  <%= number_field_tag :position, station.position_in(@route) %>
                  <%= hidden_field_tag :route_id, @route.id %>
                  <%= submit_tag 'Изменить' %>
              <% end %>
            </td>
            <td>
              <%= form_tag update_arrival_departure_admin_railway_station_path(station), method: :patch do %>
                <%= datetime_field_tag :arrival_time, station.arrive_in(@route) %>
                <%= datetime_field_tag :departure_time, station.departure_in(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag 'Сохранить' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</p>

<p>
<% if @trains.any? %>
    <strong>Поезда на маршруте:</strong>
      <ul>
      <% @trains.each do |train| %>
          <li><%= train.number %></li>
      <% end %>
        </ul>
<% else %>
      На маршруте поездов нет.
<% end %>
  </p>


  <%= link_to t('common.edit'), edit_admin_route_path(@route) %> |
  <%= link_to t('common.back'), admin_routes_path %>