config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    # root 'searches#show'

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_departure, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :routes do
      resources :railway_stations_routes
    end

    resources :tickets, except: [:new, :create]
  end

  resource :search, only: [:show]
  resources :tickets, except: [:edit, :update]
  resources :trains, only: [:index, :show]
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @stations = RailwayStation.all
    prms = params[:start_station_id] && params[:end_station_id]
    if prms
      @start_station = RailwayStation.find(params[:start_station_id])
      @end_station = RailwayStation.find(params[:end_station_id])
      @routes = @start_station.routes & @end_station.routes
    end
  end
end

app/views/searches/show.html.erb
<h1>Поиск билета</h1>

<div class="row">
  <%= form_tag search_path, method: :get do %>
      <div class="col-md-4">
        <%= select_tag :start_station_id, options_from_collection_for_select(@stations, :id, :title), class: 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= select_tag :end_station_id, options_from_collection_for_select(@stations, :id, :title), class: 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= submit_tag "Найти", class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

<p>
  <% if @routes %>
    <table class="table">
      <tr>
        <th>Поезд</th>
        <th>Маршрут</th>
        <th>Время отправления</th>
        <th>Время прибытия</th>
        <td></td>
      </tr>
      <% @routes.each do |route| %>
        <% route.trains.each do |train| %>
          <tr>
            <td><%= train.number %></td>
            <td><%= route.title %></td>
            <td><%= @start_station.departure_time(train) %></td>
            <td><%= @end_station.arrive_time(train) %></td>
            <td><%= link_to "Купить", new_ticket_path(ticket: {start_station_id: @start_station.id, end_station_id: @end_station.id, train_id: train.id}) %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% end %>
</p>