config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    # root 'searches#show'

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_departure, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :routes do
      resources :railway_stations_routes
    end

    resources :tickets, except: [:new, :create]
  end

  resource :search, only: [:show]
  resources :tickets, except: [:edit, :update]
  resources :trains, only: [:index, :show]
end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons
  # has_many :users, through: :tickets

  validates :number, presence: true#, format: {with: /^[а-яa-z\d]{3}-?[а-яa-z\d]{2}$/i, uniqueness: true}

  def places_count(wagon_type, place_type)
    wagons.where(wagon_type: wagon_type).sum("#{place_type}_places")
  end

  # def arrive_time(station)
  #   RailwayStationsRoute.where(railway_station_id: station.id).first.arrival_time
  # end
  #
  # def departure_time(station)
  #   RailwayStationsRoute.where(railway_station_id: station.id).first.departure_time
  # end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to [:admin, @train]
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id )
  end
end

app/views/admin/trains/_form.html.erb
<%= form_for([:admin, @train]) do |f| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :route %>
    <%= f.collection_select :route_id, Route.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: @train.new_record? ? 'Создать' : 'Изменить') %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to t('common.show'), [:admin, train] %></td>
  <td><%= link_to t('common.edit'), edit_admin_train_path(train) %></td>
  <td><%= link_to t('common.delete'), [:admin, train], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Список поездов</h1>

<table class="table table-condensed">
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить поезд', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<h1>Поезд №<%= @train.number %></h1>

<strong>Вагоны:</strong>
<p>
  <% if @train.wagons.any? %>
      <table class="table table-condensed">
        <%= render partial: 'admin/wagons/table_header' %>
        <% @train.wagons.ordered(@train.sort_from_head).each do |wagon| %>
            <tr>
              <td><%= wagon.train.number %></td>
              <td><%= wagon.number %></td>
              <td><%= wagon.type %></td>
              <td><%= wagon.upper_places %></td>
              <td><%= wagon.lower_places %></td>
              <td><%= wagon.side_upper_places %></td>
              <td><%= wagon.side_lower_places %></td>
              <td><%= wagon.sitting_places %></td>
              <td><%= link_to t('common.show'), admin_wagon_path(wagon) %></td>
              <td><%= link_to t('common.edit'), edit_admin_wagon_path(wagon) %></td>
              <td><%= link_to t('common.delete'), admin_wagon_path(wagon), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
            </tr>
        <% end %>
      </table>
<% else %>
    нет
<% end %>
</p>

<p>
  <%= link_to 'Добавить вагон', new_admin_train_wagon_path(@train) %>
</p>

<p>
<strong>На станции:</strong>
<% if @train.current_station %>
      <%=	@train.current_station.title %>
<% else %>
      Не указано
<% end %>
</p>

<p>
<% if @train.route %>
      <strong>Маршрут:</strong>
      <%= @train.route.title %>
<% else %>
      Маршрут не назначен
<% end %>
</p>

<%= link_to t('common.edit'), edit_admin_train_path(@train) %> |
<%= link_to t('common.back'), admin_trains_path %>