config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    # root 'searches#show'

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrival_departure, on: :member
    end

    resources :trains do
      resources :wagons, shallow: true
    end

    resources :routes do
      resources :railway_stations_routes
    end

    resources :tickets, except: [:new, :create]
  end

  resource :search, only: [:show]
  resources :tickets, except: [:edit, :update]
  resources :trains, only: [:index, :show]
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutu - Administrator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice" class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
    <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
    <p>Аккаунт: <%= current_user.email %></p>
<% else %>
    <%= link_to 'Войти', new_user_session_path %>
<% end %>

<%= yield %>

<%= render 'common/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tutu11" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Railway</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <% if current_user.admin? %>
                    <li><%= link_to 'Станции', admin_railway_stations_path %></li>
                    <li><%= link_to 'Поезда', admin_trains_path %></li>
                    <li><%= link_to 'Маршруты', admin_routes_path %></li>
                    <li><%= link_to 'Билеты', admin_tickets_path %></li>
                <% else %>
                    <li><%= link_to 'Поиск билетов', search_path %></li>
                    <li><%= link_to 'Мои билеты', tickets_path  %></li>
                <% end %>
                <li><%= link_to "Выйти", destroy_user_session_path, method: :delete  %></li>
            <% else %>
                <li><%= link_to "Войти", new_user_session_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <%= render 'common/footer' %>

    </div> <!-- /container -->

  </body>
</html>